### PR TITLE
Add recursive types

### PR DESCRIPTION
**Pull request by Mxchaeltrxn**
@haydn ... I didn't really see much else to add on top of what you wrote. I just added some description fields to the string inputs as defaults. Maybe they should be called defaultDescription.

If there are other things to add, just let me know. #86

### CODE REVIEW

**Comment by haydn** [comment]
@Mxchaeltrxn Sweet, glad it made sense to you!

Sorry, I should have been clearer in the original issue. The real goal here it to build the UI in the editor. If a component was defined in the config that had recursive options as described in those types, how would the editor display those options in the UI?

This is going to be a tricky piece of work because there’s no limit on how deep the recursion can go. If you’re keen to tackle it I’d recommend trying to mock it up in something like code sandbox, js fiddle or code pen first to get a feel for some different ways of approaching it.

**Comment by Mxchaeltrxn** [comment]
@haydn Sure. What about something simple like this (as a design). I just got this from the Mac Finder application. I feel like the problem is the limited real estate because it's just a small box in the corner of the screen. I can't imagine how it'd be pleasant working with a lot of nesting when with so little space. I'll try and tackle this one this week.

image

**Comment by haydn** [comment]
@Mxchaeltrxn Sorry for the slow reply. It was a busy week!

Yeah, something like could work. Another place to look for inspiration could be in mobile apps (because they’re design is also constrained to a very small space) or the layers panel in Figma/Sketch or something like that.

I’d recommend just picking any one and trying to get it working. Once you’ve got the recursive rendering pattern in place you’ll be able to try out different UI styles pretty easily to see how they feel and where they fall down.

**Comment by Mxchaeltrxn** [comment]
Closed in favour of #109

**Pull request closed without merging**
