### PR TITLE
Separate canvas and editor builds

### LINKED ISSUE #49: Separate the Canvas and Editor builds
Ultimately, users will need to user their own build script to make the canvas (and maybe even implement their own canvas if they've got a very different setup). That means moving the canvas into its own build and injecting it into the editor with an iframe.

---

These binaries will come with `sketchbook-js`:

- `sketchbook-editor` — starts a server running the sketchbook editor for use in a dev environment (needs an address for the canvas to be supplied)
- `sketchbook-canvas` — starts a server running the "default" canvas for use in a dev environment (renders components using React)
- `sketchbook` — starts both `sketchbook-editor` and either `sketchbook-canvas` or a custom command for launching a canvas for use in a dev environment
- `sketchbook-build-editor` — builds the editor for deploying to a production environment, baking in the config (needs an address for the canvas to be supplied)
- `sketchbook-build-canvas` — builds the canvas for deploying to a production environment, baking in the config
- `sketchbook-build` — runs both `sketchbook-build-editor` and either `sketchbook-build-canvas` or a custom command to build the canvas for deploying to a production environment

These libraries will come with `sketchbook-js`:

- `sketchbook-js/react/Canvas` — the default `Canvas` React component useful for creating a custom canvas build which might include bespoke global CSS, JS or HTML
- `sketchbook-js/react/useSketchbookCanvas` — a React hook useful for creating a custom canvas
- `sketchbook-js/{INSERT POPULAR LIBRARY HERE}/Canvas` — the `Canvas` component implemented with this specific library

Usage instructions would be something like this:

1.  Install `sketchbook-js` as a dev dependency:

    ```shell
    yarn add -D sketchbook-js
    ```

2.  You can start using the editor immediately:

    ```shell
    yarn sketchbook
    ```

3.  To mock up some components, set up a `sketchbook.config.js` file:

    ```js
    const config = {
      "My Component": {
        render: ({ width, height, options: { text } }) => text,
        options: [{ key: "text", label: "Text" }],
        init: () => ({ options: { text: "Hello World" } }),
        validate: options =>
          !options.text
            ? [{ key: "text", message: "A value for text must be provided" }]
            : null
      }
    };
    export default config;
    ```

    And pass it to the `sketchbook` command:

    ```shell
    yarn sketchbook --config=sketchbook.config.js
    ```

4.  To build for deployment to a static hosting service:

    ```shell
    yarn sketchbook-build --config=sketchbook.config.js
    ```

5.  To setup a custom canvas:

    ```shell
    yarn sketchbook --config=sketchbook.config.js --canvas-start yarn start:canvas
    ```

### PR DESCRIPTION
**Pull request by haydn**
Closes #49

### CODE REVIEW

**Comment by haydn** [comment]
@Mxchaeltrxn After experimenting with a few different approaches, I've finally got settled on using a custom webpack build script. I've limited this PR to just separating the builds so that the canvas is now loaded into an iframe and setup another issue (#74) to tackle the next part needed for the initial Storybook.js release.

Could I get you to do some testing on the branch and let me know if you run into any issues?

Some things to check:

- Running `yarn start` should start a dev server and with hot reloading enabled (modifying a source file should cause the page to automatically reload in the browser).
- Running `yarn build` should build a complete and working build into the `/build` folder (you should be able to test the build using something like [Servør](https://github.com/lukejacksonn/servor) to serve the `/build` folder).
- Running `yarn test` should report any ESLint errors, Prettier formatting issues or failing test cases.

**Comment by Mxchaeltrxn** [comment]
@haydn I'll check this now. I just saw it

**Comment by Mxchaeltrxn** [comment]
yarn start: 
```
❯ yarn start
yarn run v1.22.0
$ node scripts/start
Canvas Build: 30579
Editor Build: 30580
Server: undefined
events.js:177
      throw er; // Unhandled 'error' event
      ^

Error: spawn servor ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn servor',
  path: 'servor',
  spawnargs: [
    '/Documents/sketchbook/build',
    'index.html',
    8080,
    '--reload',
    '--browse'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

yarn test:
```
❯ yarn test
yarn run v1.22.0
$ yarn eslint && yarn jest
$ eslint src/**.js
$ jest
 FAIL  src/layers.test.js
  ● Test suite failed to run

    Cannot find module '@babel/plugin-proposal-numeric-separator' from '/Documents/sketchbook'

      at Function.module.exports [as sync] (node_modules/resolve/lib/sync.js:72:15)
          at Array.map (<anonymous>)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.877s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

yarn build:
```
❯ yarn build
yarn run v1.22.0
$ node scripts/build
{
  errors: [
    "(undefined) Entry module not found: Error: Can't " +
      "resolve 'babel-loader' in " +
      "'/Documents/sketchbook'",
    "(undefined) Entry module not found: Error: Can't " +
      "resolve 'babel-loader' in " +
      "'/Documents/sketchbook'"
  ],
  warnings: [],
  children: [
    {
      errors: [Array],
      warnings: [],
      modules: [],
      filteredModules: 0,
      logging: [Object],
      name: undefined
    },
    {
      errors: [Array],
      warnings: [],
      modules: [],
      filteredModules: 0,
      logging: [Object],
      name: undefined
    }
  ]
}
Done.
✨  Done in 3.32s.
```

**Comment by haydn** [comment]
@Mxchaeltrxn Ah! Sorry, I should have mentioned. The dependencies have changed. You'll need to run `yarn install` first.

**Comment by Mxchaeltrxn** [comment]
@haydn no errors

**Comment by haydn** [comment]
🎉  Awesome, thanks! I'm going to merge this then.

**Pull request merged**
